# Generated by Django 5.2.15 on 2026-06-30 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('review_list', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='content',
            new_name='review_content',
        ),
        migrations.AddField(
            model_name='post',
            name='actors',
            field=models.CharField(default='미정', max_length=300),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='post',
            name='director',
            field=models.CharField(default='미정', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='post',
            name='genre',
            field=models.CharField(default='미정', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='post',
            name='rating',
            field=models.FloatField(default='0'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='post',
            name='release_year',
            field=models.IntegerField(default='0'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='post',
            name='running_time',
            field=models.IntegerField(default='0'),
            preserve_default=False,
        ),
    ]
